#!/bin/bash
# SpaceOS Agent - One-Command Deployment Script
# Usage: ./deploy_spaceos.sh [OPTIONS]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default settings
STATION_TYPE="haven-1"
PROFILE="crewed"
PORT=7860
SIMULATION_MODE="true"
BUILD_ONLY=false

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RELEASE_DIR="$(dirname "$SCRIPT_DIR")"

# Print functions
print_header() {
    echo -e "\n${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Usage information
usage() {
    echo "SpaceOS Agent Deployment Script"
    echo ""
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -s, --station TYPE     Station type (haven-1, axiom, starlab, generic) [default: haven-1]"
    echo "  -p, --profile PROFILE  Operational profile (uncrewed, crewed, experiment, docking, safe_mode) [default: crewed]"
    echo "  --port PORT           Dashboard port [default: 7860]"
    echo "  --simulation          Enable simulation mode (true/false) [default: true]"
    echo "  --build-only          Only build Docker image, don't start"
    echo "  -h, --help            Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                                    # Deploy with defaults"
    echo "  $0 -s axiom -p crewed                # Deploy Axiom station in crewed mode"
    echo "  $0 -s haven-1 -p docking --port 8080 # Deploy with custom port"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -s|--station)
            STATION_TYPE="$2"
            shift 2
            ;;
        -p|--profile)
            PROFILE="$2"
            shift 2
            ;;
        --port)
            PORT="$2"
            shift 2
            ;;
        --simulation)
            SIMULATION_MODE="$2"
            shift 2
            ;;
        --build-only)
            BUILD_ONLY=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Main deployment
main() {
    print_header "🚀 SpaceOS Agent Deployment"
    
    echo "Configuration:"
    echo "  Station Type: $STATION_TYPE"
    echo "  Profile: $PROFILE"
    echo "  Port: $PORT"
    echo "  Simulation: $SIMULATION_MODE"
    echo ""
    
    # Check Docker
    print_header "Checking Docker..."
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    print_success "Docker found: $(docker --version)"
    
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        print_error "Docker Compose is not installed."
        exit 1
    fi
    print_success "Docker Compose found"
    
    # Create environment file
    print_header "Configuring Environment..."
    ENV_FILE="$RELEASE_DIR/.env"
    
    if [ ! -f "$ENV_FILE" ]; then
        cat > "$ENV_FILE" << EOF
# SpaceOS Agent Environment Configuration
# Generated by deployment script

# Station Configuration
STATION_TYPE=$STATION_TYPE
PROFILE=$PROFILE
SIMULATION_MODE=$SIMULATION_MODE

# API Keys (optional - system works without but benefits from LLM)
# Get your free API keys from:
# Google: https://aistudio.google.com/app/apikey
# Groq: https://console.groq.com/keys
GOOGLE_API_KEY=
OPENAI_API_KEY=
GROQ_API_KEY=

# Logging
LOG_LEVEL=INFO
EOF
        print_success "Created environment file: $ENV_FILE"
        print_warning "Please add your API keys to $ENV_FILE for full functionality"
    else
        print_success "Using existing environment file"
    fi
    
    # Update docker-compose with settings
    print_header "Updating Docker Compose..."
    COMPOSE_FILE="$RELEASE_DIR/docker/docker-compose.yml"
    
    # Build Docker image
    print_header "Building Docker Image..."
    cd "$RELEASE_DIR"
    
    if docker build -t spaceos/agent:latest -f docker/Dockerfile .. 2>&1; then
        print_success "Docker image built successfully"
    else
        print_error "Docker build failed"
        exit 1
    fi
    
    if [ "$BUILD_ONLY" = true ]; then
        print_success "Build complete! Image: spaceos/agent:latest"
        exit 0
    fi
    
    # Start services
    print_header "Starting SpaceOS Agent..."
    
    # Run with docker-compose
    STATION_TYPE=$STATION_TYPE \
    PROFILE=$PROFILE \
    SIMULATION_MODE=$SIMULATION_MODE \
    docker-compose -f "$COMPOSE_FILE" up -d
    
    print_success "Services started!"
    
    # Wait for health check
    print_header "Checking Service Health..."
    sleep 5
    
    # Check if service is running
    if docker ps | grep -q spaceos-agent; then
        print_success "Container is running"
    else
        print_error "Container failed to start"
        docker-compose -f "$COMPOSE_FILE" logs
        exit 1
    fi
    
    # Final message
    print_header "🎉 Deployment Complete!"
    echo ""
    echo "SpaceOS Agent is now running:"
    echo "  • Dashboard: http://localhost:$PORT"
    echo "  • Station: $STATION_TYPE"
    echo "  • Profile: $PROFILE"
    echo ""
    echo "Useful Commands:"
    echo "  View logs:    docker-compose -f $COMPOSE_FILE logs -f"
    echo "  Stop:        docker-compose -f $COMPOSE_FILE down"
    echo "  Restart:     docker-compose -f $COMPOSE_FILE restart"
    echo ""
}

# Run main
main

