rule_settings:
  disable:
  - sum-comprehension
  - use-itertools-product
  - use-assigned-variable
  - ternary-to-if-expression
  - use-string-remove-affix
  - remove-redundant-if
  - use-named-expression
  - return-or-yield-outside-function
  - simplify-negative-index
  - simplify-boolean-comparison
  - remove-redundant-path-exists
  - use-ternary-operator
  - remove-str-from-print
  - split-or-ifs
  - simplify-constant-sum
  - simplify-single-exception-tuple
  - return-outside-function
  - tuple-literal
  - use-any
  - remove-zero-from-range
  - use-count
  - use-object-destructuring
  - replace-apply-with-method-call
  - remove-redundant-slice-index
  - use-next
  - remove-unit-step-from-range
  - simplify-fstring-formatting
  - simplify-generator
  - simplify-division
  - use-join
  - assign-if-exp
  - replace-dict-items-with-values
  - swap-variable
  - replace-interpolation-with-fstring
  - use-file-iterator
  - use-datetime-now-not-today
  - remove-str-from-fstring
  - throw-new-errors
  - use-isna
  - swap-if-else-branches
  - remove-unnecessary-else
  - use-fstring-for-concatenation
  - swap-if-expression
  - simplify-numeric-comparison
  - remove-unnecessary-cast
  - simplify-len-comparison
  - while-to-for
  - yield-from
  - unwrap-iterable-construction
  - use-fstring-for-formatting
  - remove-unreachable-code
  - switch
  - str-prefix-suffix
  - remove-redundant-if-statement
  - replace-apply-with-numpy-operation
  - yield-outside-generator
  - swap-nested-ifs
  - simplify-ternary
  - use-contextlib-suppress
  - simplify-empty-collection-comparison
  - use-dictionary-union
  - use-braces
  - useless-else-on-loop
  - simplify-str-len-comparison
  - simplify-dictionary-update
  - set-comprehension
  - square-identity
  - use-dict-items
  - assignment-operator
  - remove-unused-enumerate
  - remove-redundant-fstring
  - use-or-for-fallback
  - skip-sorted-list-construction
  - use-array-literal
  - simplify-substring-search
  - while-guard-to-condition
  - remove-redundant-pass
  - use-getitem-for-re-match-groups
  - use-len
